### ISSUE TITLE
Series full of `'nan'` strings inferred as `Datetime` logical type

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#1038]
If a Series is passed to Woodwork that contains only `"nan"` strings, it gets inferred as `Datetime` logical type, filling the values with `NaT`.

```python
  nans = pd.DataFrame({
        "nans":pd.Series(['nan', 'nan', 'nan', 'nan', 'nan']),
        "nan_strings":pd.Series(['nan', 'nan', 'nan', 'nan', 'nan'], dtype='string'),
        "nan_objs":pd.Series(['nan', 'nan', 'nan', 'nan', 'nan'], dtype='object'),
       })
  nans.ww.init()

assert nans.ww.logical_types['nans'] == ww.logical_types.Datetime()
assert nans.ww.logical_types['nan_strings'] == ww.logical_types.Datetime()
assert nans.ww.logical_types['nan_objs'] == ww.logical_types.Datetime()

```

Here's the DataFrame and its dtypes before and after initialization:
![image](https://user-images.githubusercontent.com/64278226/124778382-f2255080-df0e-11eb-9541-39ee2266725a.png)

`Datetime` is definitely the incorrect logical type for these columns. What the correct logical type actually is may be up for discussion, but based off of the following behavior with `np.nan` and `pd.NA` inference, `Categorical` may be a good option that will allow for the most flexibility if values get added to the column in the future:
```python
nans = pd.DataFrame({
                            "np_nan":pd.Series([np.nan, np.nan, np.nan, np.nan]),
                            "pd_na":pd.Series([pd.NA, pd.NA, pd.NA, pd.NA]),
                            "np_nan_objs":pd.Series([np.nan, np.nan, np.nan, np.nan], dtype='object'),
                            "pd_na_objs":pd.Series([pd.NA, pd.NA, pd.NA, pd.NA], dtype='object'),
                           })

nans.ww.init()

nans.ww
```
![image](https://user-images.githubusercontent.com/64278226/124779326-afb04380-df0f-11eb-9948-84e7a9d7a976.png)

**Comment by thehomebrewnerd** [comment]
@tamargrey It seems to me that the logical type of a column with all missing values is ambiguous. Do you think it would be better to return the logical type a `Unknown` in this case (when that PR is implemented), rather than `Categorical` or some other logical type?

**Comment by tamargrey** [comment]
@thehomebrewnerd That makes a lot of sense to me. Are you thinking that a column of `np.nan` or `pd.NA` should also get inferred as Unknown? I feel like ideally, they'd all get inferred the same (though, `np.nan`s having dtype float feels deliberate in a way that I'm not as certain we should change)

**Comment by thehomebrewnerd** [comment]
My initial thought is that any column that is all null (None, np.nan, or pd.NA) should get inferred as `Unknown`, regardless of the underlying series dtype. Even though a column of missing values with a float dtype seems deliberate, we won't know that for sure, so I would be in favor of not making an assumption in that case, and requiring the user to specify the logical type for that column if they really intend for it to be a `Double`.

String representations like `"nan"` or `"None"` seem a little tricker to me. My thought is that we would treat those the same as other strings and not assume they are intended to represent missing values.

**Comment by gsheni** [comment]
Perhaps we could add a utility to Woodwork to help users replace `nan` and `None` with np.nan?

**Comment by gsheni** [comment]
Moving to Icebox as we completed the situation with nan objects 
See: https://github.com/alteryx/woodwork/pull/1043
