### ISSUE TITLE
Issues with large data sets and distributed computing

### ISSUE THREAD

**Issue by davesque** [alteryx/woodwork#1045]
This issue is related to another discussion that happened on #945 .

I noticed that some of the logic in woodwork that uses the Pandas API is also designed to accommodate Koalas or Dask objects.  For example, this utility func used by the datetime inferer:
https://github.com/alteryx/woodwork/blob/0d5c5c1ff160d35e6c50232ba0184fec860a8343/woodwork/type_sys/utils.py#L12-L35

There's an issue with the code on these lines which might exist in other places as well:
https://github.com/alteryx/woodwork/blob/0d5c5c1ff160d35e6c50232ba0184fec860a8343/woodwork/type_sys/utils.py#L15-L16

The problem is that a partitioned data set (as would be seen with Dask or Koalas) might be way too large to fit into the memory of whatever process is driving a pipeline.  So doing the `.to_pandas()` call might cause the python interpreter (or Kubernetes pod) to get OOM killed.

It may eventually become necessary for us to be more mindful of considerations involving large data sets on distributed compute clusters.  A lot of operations that are trivial to perform on a single core become difficult in a distributed setting.

Here's a link to a section in the Dask documentation regarding best practices for Dask: https://docs.dask.org/en/latest/dataframe-best-practices.html

That article has lots of good general advice on how to think about distributed data sets (e.g. cost of shuffling operations, partition size considerations, network communcation overhead, etc.).  Of course, some of the things the article mentions may be Dask-specific.  Dask has some inefficiencies baked in relating to its use of Pandas as an in-memory data representation and also its use of Python as the implementation language for its scheduler.  Some of the advice given is somewhat related to those things and wouldn't be as much of a concern with other frameworks.

**Comment by davesque** [comment]
More thoughts on this: https://github.com/alteryx/woodwork/pull/1048#discussion_r672469659

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
