### ISSUE TITLE
Change categorical inference to look at sample of 10K rows and 80% non-unique

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#1051]
- As a user, I wish I could use Woodwork to infer Categorical Logical Type. 
- This inference function would be based on a 10K sample, and 80% of the rows being non-unique. 
  - (Rather than the current implementation which looks at string length).

**Comment by davesque** [comment]
> ...and 80% of the columns being unique.

@gsheni Did you mean rows instead of columns?  Also, do you mean that 80% of rows being unique would mean it's not categorical?  I usually think of a categorical column as having a value for each row that is chosen from a relatively small number of possible unique values.

**Comment by gsheni** [comment]
@davesque Yes you are correct, I updated the issue. It should be a 10K rows sample (remove nans) + 80% of the rows being not-unique.
