### ISSUE TITLE
Perform schema init check inside method decorator 

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#1060]
- As a developer, I wish I could add the schema init check that calls `_raise_init_error` if there's no Woodwork schema on the Accessor via a method decorator instead of adding the following lines to almost every method:

```
        if self._schema is None:
            _raise_init_error()
```

Initial discussion [here](https://github.com/alteryx/woodwork/pull/1048#discussion_r669976532). Could be included as a part of #724 if the solution there is to include schema validation as a part of that raise init error step.

**Comment by simha104** [comment]
I was working on #724 and I was going to add a property for this check. I just want to confirm whether a decorator would be preferable or if I should still go ahead and make the property for the check?

**Comment by tamargrey** [comment]
@davesque @thehomebrewnerd I know there was some discussion around further updates that might allow the check to get applied without having explicitly add the decorator. Do we want to consider those further, or are we okay with moving forward with one of: decorator or property?

**Comment by thehomebrewnerd** [comment]
> @davesque @thehomebrewnerd I know there was some discussion around further updates that might allow the check to get applied without having explicitly add the decorator. Do we want to consider those further, or are we okay with moving forward with one of: decorator or property?

I think we can move forward.

What are we envisioning for the property solution here? My initial thought is that a decorator approach makes the most sense, but I guess I'm not clear on what the property solution would look like for comparison.

**Comment by simha104** [comment]
> > @davesque @thehomebrewnerd I know there was some discussion around further updates that might allow the check to get applied without having explicitly add the decorator. Do we want to consider those further, or are we okay with moving forward with one of: decorator or property?
> 
> I think we can move forward.
> 
> What are we envisioning for the property solution here? My initial thought is that a decorator approach makes the most sense, but I guess I'm not clear on what the property solution would look like for comparison.

The property solution would be to add a property to the accessor which does two things:
1. Check for whether the schema exists
2. Check for whether the schema is valid without checking for if the index is unique

**Comment by tamargrey** [comment]
the result of using a property would be that we'd still have a line or two at the beginning of each method that performs the check, which is more similar to the current setup.

```python
if not self._is_schema_invalid:
    raise schema_not_valid_error()
```

**Comment by simha104** [comment]
> the result of using a property would be that we'd still have a line or two at the beginning of each method that performs the check, which is more similar to the current setup.
> 
> ```python
> if not self._is_schema_invalid:
>     raise schema_not_valid_error()
> ```

We could both modify the property and wrap it with a decorator right?

**Comment by tamargrey** [comment]
> We could both modify the property and wrap it with a decorator right?

Yes, we could, but I think it wouldn't be necessary to have a property since it'd only need to get called once within the decorator function
