### ISSUE TITLE
Add inference for URL logical type

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/woodwork#1067]
- As a user, I wish I could use Woodwork to automatically infer if a feature is a url logical type. This would make it possible to automate the process of collecting new datasets that have url features as well as reduce the work the user has to do to specify correct types for their data. The latter is helpful for datasets with a large number of features

#### Code Example

```python
import pandas as pd
import woodwork as ww

X = pd.DataFrame({'url_feature': ["https://evalml.alteryx.com/en/stable/",
                                  "https://woodwork.alteryx.com/en/stable/guides/statistical_insights.html",
                                  "https://twitter.com/AlteryxOSS"]})
X.ww.init()

assert X.ww.logical_types['url_feature'].type_string == 'url'
```

**Comment by gsheni** [comment]
We can use this regex for the inference function
- https://urlregex.com/

**Comment by gsheni** [comment]
- Slightly modifying my earlier suggestion to 
1. Get first 100K rows (all inference functions are passed in a series which contain only the [first 100K rows](https://github.com/alteryx/woodwork/pull/1083))
2. See if the match the regex, make it an config option (https://urlregex.com/)

```python
def url_func(series: pd.Series) -> bool:
    regex = ww.config.get_option('url_inference_regex')

    # Includes a check for object dtypes
    if not pdtypes.is_string_dtype(series.dtype):
        return False

    try:
        series_match_method = series.str.match
    except (AttributeError, TypeError):
        # This can happen either when the inferred dtype for a series is not
        # compatible with the pandas string API (AttributeError) *or* when the
        # inferred dtype is not compatible with the string API `match` method
        # (TypeError)
        return False
    matches = series_match_method(pat=regex)

    return matches.sum() == matches.count()
```
