### ISSUE TITLE
Warning "Insufficient elements for `head`" getting raised many times in dask tests

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#1096]
I noticed the following warning getting raised a decent amount in our test suite: `UserWarning: Insufficient elements for `head`. 100000 elements requested, only 4 elements available. Try passing larger `npartitions` to `head`.`

Seems like it's about doubled the number of warnings that show up in our test suite, and from what I can tell, it was introduced in #1083 (which makes sense since it's a warning about `head`!). None of these warnings show up if I uninstall dask.

If it's problematic to check the length of a dask DataFrame and only call `head` when it's long enough, we don't have to worry too much about it (maybe we can suppress it?). But figured I'd bring it up!

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
