### ISSUE TITLE
Create DataTable from DataColumn(s)

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#110]
- We want users to be able to create a DataTable from a DataColumn or a list of DataColumns
- We should prevent errors (2 Data Columns with index tag)
```python

import pandas as pd 
author = ww.DataColumn(pd.Series(['bob', 'tom', 'jake', 'blue']))
article = ww.DataColumn(pd.Series([210, 211, 114, 178])  

datatable = ww.DataTable({ 'Author': auth_series, 'Article': article_series })
--

**Comment by thehomebrewnerd** [comment]
@gsheni Is this issue still valid? If so, with the accessor approach we will probably need to do this through a utility function (something like `init_from_columns` maybe), instead of through the accessor `init`.

If we keep this and use the accessor approach I think the flow would be something like this:
```python
import pandas as pd
import woodwork as ww

author = pd.Series(['bob', 'tom', 'jake', 'blue'], dtype='string')
author.ww.init(logical_type='NaturalLanguage')
article = pd.Series([210, 211, 114, 178], dtype='Int64')
article.ww.init(logical_type='Integer')

df = ww.init_from_columns({ 'Author': author, 'Article': article })
assert df.ww.schema is not None
assert df.ww.logical_types['author'] == NaturalLanguage
assert df.ww.logical_types['article'] == Integer
```

**Comment by gsheni** [comment]
Iceboxing for now. Its a low priority issue, since users can use DataFrames and Series like this to have a similar behavior
```python
d = {'col1': pd.Series([1, 2]), 'col2': pd.Series([3, 4])}
df = pd.DataFrame(data=d)
```

**Comment by gsheni** [comment]
No longer applicable.
