### ISSUE TITLE
Email Regex Edge Cases

### ISSUE THREAD

**Issue by chukarsten** [alteryx/woodwork#1101]
I believe the following test should pass.  I'm going from the super reliable [wikipedia page](https://en.wikipedia.org/wiki/Email_address) which states that the "printable characters" `!#$%&'*+-/=?^_`{|}~` should be legal.  The bullet afterward about the location of the dot character not being at the beginning or the end implies that the previously mentioned printable characters should be allowed anywhere within the local part of the email address.  

Two email addresses just so happen to fail the EmailAddress regex in the woodwork accessor `init()`.  Feel free to tell me that these either aren't valid email addresses or aren't going to be supported.

```python
from woodwork.logical_types import EmailAddress
def test_ww_email():

    X = pd.DataFrame({"email": [
                    "abalone_0@gmail.com",
                    "AbaloneRings@yahoo.com",
                    "abalone_2@abalone.com",
                    "$titanic_data%&@hotmail.com", # Problem Email
                    "foo*EMAIL@email.org", # Problem Email
                    "evalml@evalml.org",
                    "evalml@alteryx.org"
    ]})
    X.ww.init()
    assert isinstance(X.ww.logical_types["email"], EmailAddress)

```

**Comment by gsheni** [comment]
@chukarsten Is this an edge case that won't show up in most datasets? If so, I would hesitate to modify our current inference which uses a regex that we got from https://emailregex.com/.

**Comment by chukarsten** [comment]
@gsheni Yea, I'm not sure what went into generating these email addresses.  I've personally never seen email addys with "*" or starting with special characters.  Just wanted to get the issue on your board though, feel free to close!  I've changed the offending email addresses on our side to be less offensive to the regex.

**Comment by gsheni** [comment]
Closing for now.
