### ISSUE TITLE
Verify support for Datetime with timezone

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#111]
- We should verify that we can support inputted datetime columns with a timezone. 
- We should determine if we want to extract the timezone, and store it on the Datetime Logical Type. (Can some rows have different timezone than others or do all datetimes have the same timezone?)
- These will show up as `datetime64[ns, tz]` pandas dtype

**Comment by jeff-hernandez** [comment]
Do we want to store the timezone on the logical type and remove it from the series by converting the series to the current physical type (`datetime64[ns]`)?

**Comment by gsheni** [comment]
Yes, you could convert the series to UTC, and store the timezone on the Logical Type.
But this issue is about making sure we could support the following situations
1. A series with no timezone
2. A series with UTC timezone
3. A series with an actual timezone (let's say ET)

**Comment by jeff-hernandez** [comment]
If i’m understanding the approach correctly, then I think we’d handle those situations as follows:
- A series with no timezone will remain as `datetime64[ns]` and the logical type will have no timezone.
- A series with UTC timezone will be converted to `datetime64[ns]` and the logical type will store the UTC timezone
- A series with ET timezone will be converted to `datetime64[ns]` and the logical type will store the ET timezone

**Comment by gsheni** [comment]
Sounds good.
