### ISSUE TITLE
Setting new logical type with set_types drops user set semantic tags

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#1130]
Setting a new logical type with `set_types` can cause previously set semantic tags to be lost. This behavior seems a bit counter-intuitive when users do not specify new tags. If users do not specify new values for semantic tags during the call to `set_types` any previously set semantic tags should be retained.

### Current Behavior
Custom tag on `vals` column is lost
```python
import pandas as pd
import woodwork as ww

df = pd.DataFrame({'id': [0, 1, 2], 'vals': [True, False, True]})
df.ww.init(semantic_tags={'vals': 'custom_tag'})

df.ww
```
```
       Physical Type Logical Type Semantic Tag(s)
Column                                           
id             int64      Integer     ['numeric']
vals            bool      Boolean  ['custom_tag']
```
```python
df.ww.set_types({'vals': 'boolean_nullable'})
df.ww
```
```
       Physical Type     Logical Type Semantic Tag(s)
Column                                               
id             int64          Integer     ['numeric']
vals         boolean  BooleanNullable              []
```

### Expected Behavior
Custom tag on `vals` column is retained
```python
import pandas as pd
import woodwork as ww

df = pd.DataFrame({'id': [0, 1, 2], 'vals': [True, False, True]})
df.ww.init(semantic_tags={'vals': 'custom_tag'})

df.ww
```
```
       Physical Type Logical Type Semantic Tag(s)
Column                                           
id             int64      Integer     ['numeric']
vals            bool      Boolean  ['custom_tag']
```
```python
df.ww.set_types({'vals': 'boolean_nullable'})
df.ww
```
```
       Physical Type     Logical Type Semantic Tag(s)
Column                                               
id             int64          Integer     ['numeric']
vals         boolean  BooleanNullable  ['custom_tag']
```

**Comment by gsheni** [comment]
Changing the Logical Type could mean that the old semantic tag no longer applies

**Comment by gsheni** [comment]
Additionally, you could have a parameter that specifies whether or not to drop tags (when calling `set_types`).

**Comment by tamargrey** [comment]
Potential already existing bug in featuretools' usage of `set_types` in `add_relationship`: https://github.com/alteryx/featuretools/blob/main/featuretools/entityset/entityset.py#L365

**Comment by davesque** [comment]
@gsheni @thehomebrewnerd @tamargrey Is there a reliable programmatic way that we track which tags belong to which types?

I'm seeing this utility function here:
https://github.com/alteryx/woodwork/blob/96d31b8a00ff405377441c78ee702cebfa937a81/woodwork/type_sys/utils.py#L102.

However, that looks like it includes some ad hoc stuff such as the way it specifies tags that are compatible with all types.

Relatedly, do we allow users to set their own custom tags?  If so, we may not have a way of determining whether a tag is compatible with a type.

**Comment by thehomebrewnerd** [comment]
> Is there a reliable programmatic way that we track which tags belong to which types?

Sort of. Standard tags which belong to logical types are defined on the `LogicalType.standard_tags` attribute. That is the most reliable way to determine the tags that belong to specific logical types.

However, the whole picture is a little more complicated. I think there are a few types of tags that are treated differently:
- Standard tags, which are defined on the LogicalType class: these are tags that we as Woodwork devs have determined should be applied to certain logical types, primarily `numeric` and `categorical` columns. These tags are really meant to indicate that any columns with these tags applied can be used in numeric operations (like adding two columns together) or contain categorical values.
- `index` and `time_index` tags: These are special tags that can be applied to certain columns only. They aren't necessarily tied to a specific LogicalType, but the data contained in those columns must meet certain criteria - for example, index columns must be unique. Users cannot add these tags directly, they only get set through operations like `set_index`.
- Custom tags: Anything else. If users want to create their own tag, they are free to do so, but they must make sure they are applying and using it properly. We have no mechanism in place to determine whether or not a custom tag is compatible with a given logical type - the creator/user of the custom tag must take on that burden.

For the most part, I think that outside of the "standard tags" which are defined on the LogicalType class, there is not a notion of compatibility between semantic tags and logical types. Having said that, we have defined a few other tags (like "date_of_birth") that have special meaning, primarily in the Featuretools usage of Woodwork. That is why you are seeing that "ad hoc" code in the `list_semantic_tags` function - because we are suggesting to users that the "date_of_birth" tag should only be used on datetime columns, but there is no checking or enforcement of that inside of Woodwork.

I'm not sure that helps or confuses things further. Happy to chat more about all this if needed.

**Comment by tamargrey** [comment]
@davesque It might be worth noting that the restrictions around the `index` and `time_index` tags only exist on Woodwork DataFrames. A Woodwork Series will not restrict the use of those tags, because the concept of a woodwork index isn't applicable to a series. 

So the following is perfectly acceptable:
```python
es = make_ecommerce_entityset()

col = es['log'].ww['latlong']
col.ww.add_semantic_tags('time_index')
```
