### ISSUE TITLE
Datetime inference takes too long on large dataframes

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#1135]
Type inference on datetime columns takes a very long time. This can be especially problematic for large dataframes that contain several datetime columns.

As an example, initializing Woodwork on this single column dataframe takes over 15 seconds based on my local testing.

```python
import pandas as pd
import woodwork as ww

df = pd.DataFrame({'dates': ['2017-01-01']*1000000})
df.ww.init()
```

I believe a majority of this time is in the `_infer_datetime_format` utility function, but I have not confirmed for sure.

For comparison, type inference on a column of integers of the same length takes about 3 ms and inference on a column of strings takes about 275 ms.

We should further investigate why datetime inference is so slow and implement improvements to speed it up as much as possible to prevent long inference times on large datasets containing datetime columns.

**Comment by gsheni** [comment]
I am surprised this is causing a slowdown, since we only use first 100 rows:
- https://github.com/alteryx/woodwork/blob/55c7489c0db245108cce5d69a9a58ea201105a4c/woodwork/utils.py#L452

**Comment by thehomebrewnerd** [comment]
@gsheni We aren't calling this with the default value though:
 https://github.com/alteryx/woodwork/blob/55c7489c0db245108cce5d69a9a58ea201105a4c/woodwork/logical_types.py#L184-L186

**Comment by thehomebrewnerd** [comment]
Here is a performance profiling run on the example I included above:

![image](https://user-images.githubusercontent.com/4307001/132770216-ea9c65d1-c323-4549-b04f-0d5a6c689917.png)

**Comment by gsheni** [comment]
- Gotcha.
@tuethan1999 did the following
https://github.com/alteryx/woodwork/pull/1025/commits/1af46082b1a537af6e09655dbe3dac98fdfb7c45
https://github.com/alteryx/woodwork/pull/1025/commits/56e09ff5bb579f912ef7f1ac69f5186036229b6e
- So we are actually using 1/10 of the series length. With a large dataframe, I can see why this might be problematic.
- @tuethan1999 Is there a reason we can't change it to default to 100 rows (or all the rows if <100 rows)?
