### ISSUE TITLE
Make `_get_subset_schema` public

### ISSUE THREAD

**Issue by eccabay** [alteryx/woodwork#1143]
With the relatively new ability to initialize `ww` objects with partial schemas, the `_get_subset_schema` method becomes incredibly useful. It would be great to have this method be public so we can use it in evalml, as discussed [here](https://github.com/alteryx/evalml/pull/2774#discussion_r708304796)

**Comment by gsheni** [comment]
@eccabay thanks for filing the request. Since this isn't mission critical, we will backlog this for now and address it later on.

**Comment by jeff-hernandez** [comment]
closed by #1218
