### ISSUE TITLE
Add PhoneNumber inference function

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#1146]
- We can potentially use a regex to infer phone numbers
- https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s02.html

**Comment by tamargrey** [comment]
If the regex we use only works for north american numbers, does the logical type need to be named as such?

**Comment by gsheni** [comment]
Good question.
So similar to how PostalCode supports other countries (and is named such), we can say that PhoneNumber is generic for the whole world. Given that this is just the inference function, we can support inferring North America numbers for now.
