### ISSUE TITLE
Datetime column frequency inference V2

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#1208]
In #1202, we added the ability to infer frequencies for temporal (datetime and timedelta) columns in a Woodwork dataframe. This inference is called for by the user and is not stored anywhere on the DataFrame. It also only works for pandas DataFrames. 

There are a number of improvements we could make. They are listed here, and we can create individual issues if any of these become necessary to implement.

- Store inferred frequency in the Woodwork typing info
  - Should likely be stored on the Datetime logical type object
  - If stored on Datetime logical type object, we need to implement validation in `Datetime.transform` (or the validation method if #1192 has implemented a `LogicalType.validate` method)
- If we can store the frequency, automatically infer the frequency for time index columns and store it
- Add frequency inference as column accessor method as well - can automatically store on logical type
- Sort columns passed to `infer_temporal_frequencies` before trying to infer frequencies
  - from @freddyaboulton : I would say no until we figure out how often/useful it is to infer frequencies on multiple datetime columns. My hunch is that most users will only care about the time_index which will already be sorted so let's not double sort for now. Of course, users can have a non-sorted time_index but I don't think there's anything we can do about that.
- Only pass a single subset (must be taken consecutively from series) to use for frequency inference
  - from @freddyaboulton: I am on the fence about this. I think we would need to do some experimentation to see what results we get with taking a sample vs not. My guess is that it's ok to do so. If we can't infer a frequency on the first k rows, we're not going to be able to infer a frequency on the whole column. In my opinion the right thing to do is to take the first-order diff of all rows and find the frequency that works the best for the most rows (like what's mentioned in #1165 for datetime format inference) but that seems like a v2 improvement?

- Use multiple subsets of data (that's long enough) for frequency inference and take the mode of non-null inferred frequencies 
- Implement for Dask and Koalas dataframes as well (if using just a subset of data, this will be doable)

**Comment by gsheni** [comment]
@tamargrey Can we support irregularly spaced time frequencies? My guess is `pandas` doesn't support it, so we would have to implement our own...
