### ISSUE TITLE
Add CurrencyCode Logical Type (ISO 4217)

### ISSUE THREAD

**Issue by willsmithorg** [alteryx/woodwork#1227]
I would like to add CurrencyCode as a logical type.  The universal standard for these is the ISO 4217.  I work in finance and almost every dataset contains CurrencyCodes.

Please assign this issue to me.  I'm happy to work on a PR to add and detect this logical type.

**Comment by gsheni** [comment]
@willsmithorg thanks for creating this issue. I have assigned you the issue.

**Comment by willsmithorg** [comment]
Hi Gaurav

I tried making CurrencyCode a child of Categorical, but I would like to add an inference function.  It's very easy to detect a feature containing currency codes for a human, not too hard to code, and there should be very minimal false positives and negatives.  Unfortunately when I make CurrencyCode a child of Categorical, the inference function is not called because only top level logical datatypes are considered for inference right now:
https://github.com/alteryx/woodwork/blob/4d32985996cb8e5e935b6595eabdc73c5b317acc/woodwork/type_sys/type_system.py#L321

Currently I've changed the design and made CurrencyCode a string instead, and the inference function now triggers.  I'm tidying up the last few tests.

But the design feels wrong - there are only ~200 possible ISO4217 currency codes, so it's really a categorical.  The same with CountryCode, which I notice doesn't yet have an inference function.

I'm guessing the vision is to have inference functions as much as possible, at least where a human could easily make the inference?  What are you suggestions?

Thanks
Will

**Comment by willsmithorg** [comment]
I think I'm close to an answer - could you tell me if I'm right?
CurrencyCode _can_ be a child of Categorical, but the inference function for CurrencyCode won't be tested unless it's first inferred as Categorical.
And Categorical looks for the number of duplicate values, which is why the existing Categorical positive test cases look like this, with lots of duplicates:

        pd.Series(10 * ["a", "b", "a", "b"]),

and my test case didn't pass Categorical, so wasn't triggering the CurrencyCode inference function, because my test was just:
      pd.Series(['USD', 'GBP', 'CAD', 'EUR'])

So I can fix this by once again making CurrencyCode a Categorical, and makign my test :

      pd.Series(10 * ['USD', 'GBP', 'CAD', 'EUR'])

The only problem I see is if a dataset contained say just 100 rows containing 100 unique currencies, it's clearly a CurrencyCode logicaltype to a human, but it won't get past the Categorical inference test.  I suspect this is an edge case.

**Comment by thehomebrewnerd** [comment]
@willsmithorg Sounds to me like you are on the right track here. As you discovered, we set up inference to only call inference functions for child types when the parent inference is a match for the column. This was primarily done for efficiency reasons to avoid calling inference functions unnecessarily, with the idea that if a column is not a match for a more general parent type, then it by default wouldn't be a match for a more specific child type.

That setup assumes that the inference functions build on each other in a sense and become more specific as you traverse the parent-child relationships. That doesn't necessarily have to be the case here though, where you could instead do something like checking column values against a known list of currency codes and not worry about duplicate values. That results in the problem you have identified in a dataset with a small number of unique rows, without a great way to solve it currently without breaking the parent-child relationship.

Anyway, I just wanted to provide a little context. My suggestion would be to have `CurrencyCode` be a child type of `Categorical` as you are doing, with the recognition that we might not get the country code inference correct for columns that don't have many duplicate values (which is also a limitation for the parent `Categorical` type). If this proves to be a problem, we can create a new issue and revisit the inference process to see if we can improve. In the meantime, users always have the ability to manually set the type for a column if it is inferred incorrectly, but hopefully this would only happen in a small number of edge cases like the one you mention.

**Comment by willsmithorg** [comment]
Thanks @thehomebrewnerd .  I will continue with the PR with `CurrencyCode` as a child of `Categorical` as you suggest.
