### ISSUE TITLE
Contributing guide does not mention need to install java.

### ISSUE THREAD

**Issue by willsmithorg** [alteryx/woodwork#1231]
[a description of what documentation you believe needs to be fixed/improved]
I am using an default Amazon Machine Image (AMI).

I followed the instruction in contributing.md

When I tried to run tests ('make test')  without making any code changes, every tests failed with a warning about pyspark, for example:
```
ERROR woodwork/tests/test_config.py::test_init_conifg - Exception: Java gateway process exited before sending its port number
```

I traced this back to the need to install java.  So on Amazon, I need to run:
```
sudo amazon-linux-extras install java-openjdk11
```

After that all the tests succeeded.   Could 'contributing.md' maybe include more detail on how to do this, or could the "make installdeps" script maybe do this?

**Comment by gsheni** [comment]
Thanks for the suggestion! We have updated our contributing document to include this information.

**Comment by chukarsten** [comment]
I had this issue.  Wasn't sure whether the brew commands were supposed to do this for me.  But ultimately had to run `echo export "JAVA_HOME=\$(/usr/libexec/java_home -v 11.0.11)" >> ~/.bash_profile` and restart my mac terminal to get it to take and run the tests.

**Comment by chukarsten** [comment]
As a side note, getting the tests to run in Pycharm involve setting the env-var in the individual run configurations for the test to `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`
