### ISSUE TITLE
Tuple type columns incorrectly inferred as EmailAddress logical types

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#1248]
Woodwork's default inference currently identifies columns that have latlong like values stored in tuples as `EmailAddress`. We should update the EmailAddress inference so that these columns are identified as `Unknown` until proper LatLong type inference is added.

```python
import pandas as pd
import woodwork as ww

df = pd.DataFrame({"tuple_ints": pd.Series([(1, 2), (3, 4)]),
                   "tuple_strings": pd.Series([("1", "2"), ("3", "4")]),
                   "string_tuple": pd.Series(["(1, 2)", "(3, 4)"])})
df
```

```
  tuple_ints tuple_strings string_tuple
0     (1, 2)        (1, 2)       (1, 2)
1     (3, 4)        (3, 4)       (3, 4)
```

```python
df.ww.init()
df.ww
```
```
              Physical Type  Logical Type Semantic Tag(s)
Column                                                   
tuple_ints           string  EmailAddress              []
tuple_strings        string  EmailAddress              []
string_tuple         string       Unknown              []
```

**Comment by gsheni** [comment]
I wonder if a better behavior is a LatLong inference that says if a tuple is found, it's LatLong.

**Comment by thehomebrewnerd** [comment]
> I wonder if a better behavior is a LatLong inference that says if a tuple is found, it's LatLong.

@gsheni Yeah, a quick and easy inference for lat-long could just be a check for a tuple or more specifically a two-tuple, but that might miss some values that aren't actually stored in a tuple, but in a string equivalent.

Regardless, the email address inference function should not be returning `True` if the input is a tuple, which seems to be the case based on the behavior above.

**Comment by gsheni** [comment]
Yah a good first pass is to check for two tuple, and then say its LatLong. 

Agree on the Email Address behavior.

**Comment by dvreed77** [comment]
Inferring LatLong types are already described in ticket #12
