### ISSUE TITLE
Update koalas code to pyspark pandas API instead in Woodwork

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#1263]
The koalas library is now in maintenance mode only, and the core code has been integrated into pyspark, starting with version 3.2. We should update our koalas specific code to use the new pyspark pandas API: https://spark.apache.org/docs/latest/api/python/migration_guide/koalas_to_pyspark.html

**Comment by gsheni** [comment]
We should make sure we can support python 3.10 with the latest Koalas.

**Comment by jeff-hernandez** [comment]
By updating, are we removing and replacing koalas-specific code with the new pyspark pandas API?

**Comment by gsheni** [comment]
@jeff-hernandez yes

**Comment by jeff-hernandez** [comment]
@gsheni it sounds like we are removing koalas, so not sure how we want to support the latest koalas with this update

**Comment by gsheni** [comment]
Sorry, I meant support latest python 3.10 with pyspark (which replaces koalas).
