### ISSUE TITLE
Stop using df.append in codebase to resolve warning

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#1493]
- In building the Featuretools docs I saw this warning
```python
/Users/gaurav.sheni/.pyenv/versions/3.9.13/lib/python3.9/site-packages/woodwork/type_sys/utils.py:132: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```
- We should remove `df.append` and use `df.concat`
- Completion: No more `.append` calls in Woodwork

**Comment by sbadithe** [comment]
I might be misunderstanding something, but I think it's worth noting that `pd.concat` works on `Pandas` series and data frames. In parts of the code where the series or dataframe can be Dask or PySpark, a call to `pd.concat` would fail.

**Comment by gsheni** [comment]
@sbadithe We should use the correct call for concat, and can check the dataframe type
