### ISSUE TITLE
Improve Woodwork error message for invalid init calls

### ISSUE THREAD

**Issue by bchen1116** [alteryx/woodwork#1569]
If we do
```python
df = pd.Series(["90210", "60018", "10010"] * 100)
df.ww.init()
```
we get the following error:
```python
raise TypeValidationError(
woodwork.exceptions.TypeValidationError: Cannot initialize Woodwork. Series dtype 'object' is incompatible with PostalCode LogicalType. Try converting series dtype to 'category' before initializing or use the woodwork.init_series function to initialize.
```

If we were to follow the first recommendation, we get the following:
```python
df = pd.Series(["90210", "60018", "10010"] * 100).astype('category')
df.ww.init()
df.ww.schema
->
<ColumnSchema (Logical Type = Categorical) (Semantic Tags = ['category'])>
```
The second recommended action is correct, resulting in us getting a postal code logical type.

This issue tracks fixing this message so that users can get accurate inference on their datatables. In the case of series data, we should tell them to use `init_series` rather than `ww.init()`.

**Comment by sbadithe** [comment]
Here is an additional example where PostalCode is not inferred: 

```
>>> df  = pd.DataFrame()
>>> df['a']  = pd.Series(["90210", "60018", "10010"] * 100)
>>> df['a'] = df['a'].astype('category')
>>> df.ww.init()
>>> df.ww.logical_types
{'a': <woodwork.logical_types.Categorical object at 0x16f3e6a40>}
```

However, if we run 
```
>>> df = pd.DataFrame()
>>> df['a']  = pd.Series(["90210", "60018", "10010"] * 100)
>>> df.ww.init()
>>> df.ww.logical_types
{'a': <woodwork.logical_types.PostalCode object at 0x14dc63c10>}
```

we get the expected result.

This seems to suggest that PostalCode is not being inferred if the column has a `category` dtype.


pandas version: 1.4.4
Woodwork version: 0.20.0
