### ISSUE TITLE
Renaming columns switches the schema column order

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/woodwork#1588]
When renaming woodwork columns the order of columns in the schema also changes. Is this intended behavior?

```python
df = pd.DataFrame({"A": [1, 2, 3], "B": [1, 2, 3], "C": [1, 2, 3]})
df.ww.init()

df_renamed = df.ww.rename(rename)

assert df_renamed.ww.schema.columns == df.ww.schema.columns
```

**Comment by bchen1116** [comment]
Doesn't seem like it is intended or unintended. We don't do anything to ensure the order remains the same. Can add support for this!
