### ISSUE TITLE
Allow `ww.type_system.add_type` a warning only option *or* provide and *exists* function

### ISSUE THREAD

**Issue by ulc0** [alteryx/woodwork#1649]
- As a [user/developer], I wish I could use Woodwork to add my new logical types without always erroring if it's already added. 

Current State:
- If type is not set, add_type works, delete_type fails
- If type is set, add_type fails delete_type works

Can we have an elegant solution to this problem? So I don't have to hardcode new logicals in my own fork?

**Comment by ParthivNaresh** [comment]
@ulc0 Thanks for filing this issue, the new behaviour will allow for passing a `treatment` parameter to `add_type` and `remove_type`.

`add_type` will accept the values of `replace`, `ignore`, or the default of `None`.
- `replace` - If that logical type already exists, it will be unregistered and the parameters that were passed into the function call will be used instead.
- `ignore` - If that logical type already exists, any parameters that were passed into the function call will be ignored.
- `None` - The current behaviour will be defaulted to (raising an error)

`remove_type` will accept the values of `ignore` or the default of `None`.
- `ignore` - If that logical type doesn't exist, do nothing.
- `None` - A more descriptive error than what is currently provided will be raised (default).
