### ISSUE TITLE
Deprecate support for Spark DataFrames

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#1686]
- We would like to remove Spark support from Woodwork. 
- If you are using Spark DataFrames in Woodwork, **please leave a comment**

**Comment by ulc0** [comment]
We are using woodwork and featuretools. I would be happy to contribute if spark deprecation is related to that

**Comment by gsheni** [comment]
Due to the community feedback, we have decided not to remove Spark support in Featuretools
