### ISSUE TITLE
Add pandas Extension to support df.to_datatable 

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#17]
- Pandas has an extension functionality which can allow us to register functions to dataframes.
- This would allow a user to do `dataframe.to_datatable`
- Pandas [Doc Link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.extensions.register_dataframe_accessor.html#pandas.api.extensions.register_dataframe_accessor)

**Comment by tyler3991** [comment]
#483 addresses this. Closing
