### ISSUE TITLE
CI check: ensure docs notebooks have no outputs prior to execution

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#182]
- We use nbsphinx to re-run the notebooks and generate accurate documentation
- However, this won't work if the notebook has already been run, or partially run.
- Let's add a check in our CI that checks that all files with `ipynb` extension do not have any cell outputs.

**Comment by gsheni** [comment]
We might be able to get away with using the `nbsphinx_execute` option. 
- https://nbsphinx.readthedocs.io/en/0.8.2/usage.html#nbsphinx_execute

**Comment by gsheni** [comment]
EvalML has also run into this
- https://github.com/alteryx/evalml/issues/2566

**Comment by tamargrey** [comment]
@gsheni can this be closed now that #1153 is in?
