### ISSUE TITLE
Standard tag behavior doesn't work properly when changing DataTable index

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#199]
If a user creates a DataTable using standard tags and then sets and subsequently changes the index column, the standard tags setting that was originally present on the column is lost.

```python
data = pd.DataFrame({
    'index': [0, 1, 2],
    'id': [1, 2, 3],
})

dt = DataTable(data)
print(dt['index'].use_standard_tags)
dt.set_index('index')
print(dt['index'].use_standard_tags)
dt.set_index('id')
print(dt['index'].use_standard_tags)
```

The output of these print statements are `True, True, False` indicating the use_standard_tags setting was changed for the `index` column, when setting the index to be the `id` column. This is because in the process of changing the index `remove_semantic_tags` is called, and this always returns a column that has `use_standard_tags` set to `False`.

We need to find a better way to deal with this situation to preserve the `use_standard_tags` attribute for a column, while still allowing users to remove a standard tag they do not want.

**Comment by tyler3991** [comment]
Putting this into ice box column for now. Agree this is an issue though.

**Comment by thehomebrewnerd** [comment]
With the new accessor/schema approach, the `use_standard_tags` setting is stored on the Schema, and not on the individual columns as it was previously. As a result, this issue is no longer applicable - changing the index column has no impact on the `use_standard_tags` setting.
