### ISSUE TITLE
If use_standard_tags is false, column properties could be ignored

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#214]
Currently we use the `DataTable._new_dt_from_cols` in several places to create and return a new DataTable object. This method currently initializes and creates new column objects based on the settings stored in the DataTable. In most circumstances this is fine, but if the user has modified properties on individual DataColumns (such as `use_standard_tags`), these properties will be lost and reset to the value on the DataTable during the call to `_new_dt_from_cols`.

Once the `DataColumn.copy` method is added (Issue #175), we should update `_new_dt_from_cols` to create copies of all existing DataColumns in the table, and rebuild the new table from these columns. This will retain any individually set properties on the DataColumns. The ability to create a DataTable from DataColumns is captured in Issue #110.

As part of this update we should also remove any properties that are currently stored on both the DataTable and DataColumn, so there is only one source for the information, to avoid conflicting values from being specified.

**Comment by tyler3991** [comment]
Accessor #483 will handle this; closing.
