### ISSUE TITLE
Add method to get valid mutual info column

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#254]
Now that we skip rows for mutual information between a column and itself, we should have a way for users to determine which columns are valid for mutual info.

`dt.get_valid_mi_columns` should return a list of the columns in the datatable that are not fully null and are Boolean, Categorical, or Numeric

**Comment by tyler3991** [comment]
@tamargrey, is there a good use case for this? Should we prioritize this? 

Leaving in backlog for now.

**Comment by tamargrey** [comment]
@tyler3991 I think someone might've brought this up recently, but I can't remember in what context. Maybe @gsheni knows?

**Comment by thehomebrewnerd** [comment]
We added a function in PR #517 to return a list of the LogicalTypes that can be used in mutual information calculations, which isn't quite the same as this, but close.

**Comment by tamargrey** [comment]
@thehomebrewnerd that's exactly what I was thinking of--thanks!
