### ISSUE TITLE
Support conversion to non-nullable dtypes when no NaN values in DataTable

### ISSUE THREAD

**Issue by angela97lin** [alteryx/woodwork#257]
In the following code snippet, calling `.to_numpy()` returns an np.array with a dtype=object.
```
y = np.array([1, 0, 1])
y = pd.Series(y)
y = ww.DataColumn(y)
y.to_pandas().to_numpy()
>> array([1, 0, 1], dtype=object)
```

This causes issues in EvalML where we take the input ww.DataTable and grab the `.to_pandas()` underlying pd.DataFrame to pass to external library calls (scikit-learn). scikit-learn converts the pd.DataFrame (with dtype=Int64) to a numpy array with dtype=object, which it then complains about.

Two proposals for resolving this:
- When the DataColumn has no NaN values, use numpy dtypes (int64) instead
- Have a `.to_numpy()` method which is able to determine that a column with dtype `Int64` and no null values should be converted into an array of dtype `int64`

In the short-term, EvalML will write an utility method / wrapper when we call `.to_pandas()` to make this appropriate conversion, but this can easily get ugly and I think it would make sense to have woodwork internally handle this instead.

@gsheni @dsherry FYI!

**Comment by tyler3991** [comment]
@angela97lin, is this still an issue for EvalML? 

@tamargrey, will the upcoming series accessor address this? 

@gsheni, can you put this in the appropriate zenhub lane after comments?

**Comment by angela97lin** [comment]
No longer a blocker, as we added code in EvalML (`_convert_woodwork_types_wrapper`) to handle this case and manually convert the column type.

**Comment by tyler3991** [comment]
thanks @angela97lin  !!

**Comment by tamargrey** [comment]
@tyler3991 the accessor changes wouldn't really do anything about this. It could still be something we support at some point, though.

**Comment by tyler3991** [comment]
Got it. Thank you. Gaurav and I were just doing some issue cleanup. We'll keep this one in the "backlog" for now 😃

**Comment by gsheni** [comment]
Closing since #850 will be merged in soon.
