### ISSUE TITLE
Remove use_standard_tags from DataColumn

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#273]
- Having `use_standard_tags` is problematic because it does not allow for confidence when checking a column.
  - For example, if we want to check that a column is Numeric, we can check the Semantic Tags and look for `numeric` but if `use_standard_tags` is False, it will have not have been added forcing a check on the Logical Type
- TLDR: - It makes the semantic_tags useless having to worry about `use_standard_tags`

- In addition, primary users of Woodwork (EvalML, Featuretools), will have `use_standard_tags` True for all columns. 
- Therefore, to reduce complexity, we will remove `use_standard_tags`, and by will add standard tags to applicable DataColumns.

**Comment by tyler3991** [comment]
Closing after chatting with @gsheni
