### ISSUE TITLE
Don't allow index and time_index to be the same column

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#301]
Right now, we allow a DataTable to be made where a single column is both the `index` and the `time_index`. 
This is bad practice as an index is meant to be used as a lookup key while the time index tells you the relative order in time for a row as it relates to the index. 

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
from woodwork import DataTable
df = pd.DataFrame({
        'id': pd.Series([1, 2, 3]),
    })
dt = DataTable(df, index='id', time_index='id')
assert dt['id'].semantic_tags == {'index', 'time_index'}
assert dt.index == dt.time_index
```
#### Expected Output
We should catch this at parameter validation and also not allow this to happen when `set_index` or `set_time_index` is used.

The error message could be something like
`ValueError: The index column must be different from the time index. Please change one of the columns being assigned as index or time index.`

**Comment by tyler3991** [comment]
Ice boxing this for now. Have any users actually run into this issue?

**Comment by tamargrey** [comment]
@tyler3991 Nobody's run into this. And I think in talking about this issue back when it was created, we might have even decided there might be a time where you wanted to allow an index and time index to be the same column.

**Comment by tyler3991** [comment]
Gotcha, this helps, thank you!

**Comment by thehomebrewnerd** [comment]
This is still an issue with the accessor implementation.

Updated code:
```python
import pandas as pd
import woodwork as ww
df = pd.DataFrame({
        'id': pd.Series([1, 2, 3]),
    })
df.ww.init(index='id', time_index='id')
assert df.ww.semantic_tags['id'].semantic_tags == {'index', 'time_index'}
assert df.ww.index == df.ww.time_index
```
