### ISSUE TITLE
Let load_retail use a Dask dataframe

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#306]
#### Is your feature request related to a problem? Please describe.

I wish I could load a demo Dask dataframe instead of first loading a pandas one and converting it to Dask.

We currently do this in the Using Woodwork with Dask guide. We're also planning on adding Koalas, so it'll be nice if we could use this functionality there too. 

#### Describe the solution you'd like

We could do

```python
df_dask = ww.demo.load_retail(return_dataframe=True, dataframe_dtype='dask', npartitions=10)
dt = DataTable(df_dask)
```

or

```python
dt = ww.demo.load_retail(return_dataframe=False, dataframe_dtype='dask', npartitions=10)
```

**Comment by thehomebrewnerd** [comment]
This function has been refactored a bit with the accessor implementation, but we could still update to return a Dask/Koalas dataframe. We should also review whether we want the `init_woodwork` parameter to default to `True` or `False`.

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
