### ISSUE TITLE
Add DataTableSet class to hold collection of DataTables with relationships

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#315]
#### Add DataTableSet class to hold collection of DataTables with relationships
- Support for relationships between DataTables, with a DataTableSet containing the relationship information between the DataTables.
- Support add relationship to the DataTableSet.
- Support for normalizing a DataTable to create a new DataTable in the DataTableSet.

#### Additional context

```python
import woodwork as ww

products_dt = ww.DataTable(products_df, name='products')
transactions_dt = ww.DataTable(transactions_df, name='transactions')

datatable_set = ww.DataTableSet(name='retail')
datatable_set = datatable_set.add_datatable(products_dt)
datatable_set = datatable_set.add_datatable(transactions_dt)
new_relationship = ww.Relationship(datatable_set["products"]["product_id"], 
                                   datatable_set["transactions"]["product_id"])
datatable_set = datatable_set.add_relationship(new_relationship)

datatable_set = datatable_set.normalize_entity(base_datatable_id="transactions",
                                               new_datatable_id="sessions",
                                               index="session_id",
                                               make_time_index="session_start",
                                               additional_variables=["device", "customer_id"])
```

**Comment by thehomebrewnerd** [comment]
@gsheni With the accessor implementation, this implementation could change quite a bit from what would have been done with DataTables. Maybe we should create a new issue for this if this type of functionality is still needed.

**Comment by gsheni** [comment]
Closing in favor of: https://github.com/alteryx/woodwork/issues/752
