### ISSUE TITLE
General documentation cleanup needed

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#334]
#### Location of the documentation

Various documents need to be reviewed and updated for consistency and proper formatting.

#### Documentation problem

There are several relatively minor issues in the documentation that should be cleaned up. These include:
- Making sure that the methods in the API reference are in alphabetical order. For example, the `DataTable` methods are not currently alphabetized
- Review formatting of all docstrings to make sure description, arguments and return values are formatted properly. Might require changing indentation of docstrings to fix.
- Consistent use of periods at the end of the main method descriptions - some contain trailing periods, some do not.

**Comment by tyler3991** [comment]
After #527 , does this issue still need to be open @thehomebrewnerd ? 

If no, please close!

**Comment by thehomebrewnerd** [comment]
@tyler3991 I think this one is still valid, but it should be simple. I'll try to go through it this week and put up a PR to close this.

**Comment by tyler3991** [comment]
sounds good!
