### ISSUE TITLE
Handle Dask s3 Serialization Tests

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#336]
I wish I could test serialization of Dask DataTables with s3 URLs. 

Currently we use `xfail_tmp_dissapears` to avoid testing serialization and deserialization of Dask DataTables to s3 urls--in `test_to_csv_S3` for example. This is because when using a tempdir for tests, the Dask dataframe not being in memory means that when the tempdir gets deleted, we lose the data and cannot check for equality.

A possible solution would be to directly save the data rather than save it into a tmpfile so it doesn’t disappear. We could save the DataTable to disk before deleting the tempdir so we could use the saved table as the reference. 

To test, remove the following line from any test where it can be found.
```python
   xfail_tmp_disappears(sample_df)
```

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
