### ISSUE TITLE
Equality between Dask and Pandas DataTables

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#337]
If we have two DataTables that are identical except that the underlying data for one is Dask and Pandas for the other, they should not be equal. 

As we don't compare underlying data for any Dask DataTables in checking equality to avoid calling `compute`, we'll currently say these two DataTables are equal.

We should have a check like `df1.__class__ != df2.__class__`

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'test':[1,2,34]})
dask_df = dd.from_pandas(df,npartitions=2)

assert DataTable(df) == DataTable(dask_df)

```
#### Expected Output
`assert DataTable(df) != DataTable(dask_df)`

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
