### ISSUE TITLE
Add Pandas support for properties and methods not explicitly defined in woodwork.

### ISSUE THREAD

**Issue by ctduffy** [alteryx/woodwork#372]
We can use this extend functionality to allow methods and properties not explicitly written for our Woodwork DataTables to be used for DataTables with Pandas dataframes as the underlying data type.

- https://pandas.pydata.org/pandas-docs/stable/development/extending.html#override-constructor-properties

**Comment by tyler3991** [comment]
Closing. Duplicate of #485
