### ISSUE TITLE
Add _is_datetime to DataColumn

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#403]
- As a developer, I wish I could use Woodwork to determine if a Data Column is a Datetime Logical Type.

#### Code Example

```python
datacolumn._is_datetime()
```

**Comment by tamargrey** [comment]
@gsheni is it okay if I implement this and #402 in when moving mutual info over to the Accessor? I'll need to add `_is_numeric` and `_is_categorical` as helper functions in the `schema_column.py` file anyway.

Figure it can be a separate PR to add all 4 before moving onto mutual info, but it'll be nice to have as long as we're starting to get to the code that'll use them.

**Comment by gsheni** [comment]
@tamargrey that sounds good to me.
