### ISSUE TITLE
Docs for DataTable/DataColumn constructors: indicate if copy occurs

### ISSUE THREAD

**Issue by dsherry** [alteryx/woodwork#420]
The docs for `DataTable` currently say:
> create DataTable

With [the recent removal of the `copy_dataframe` argument](https://github.com/FeatureLabs/woodwork/pull/398), it would be nice to note whether or not this instantiation will make a full copy of the dataframe, and what the implications of that are.

Same question [for `DataColumn`.](https://woodwork.alteryx.com/en/stable/generated/woodwork.datacolumn.DataColumn.html#woodwork.datacolumn.DataColumn)

**Comment by thehomebrewnerd** [comment]
This issue no longer applies with the accessor implementation and can be closed after the completion of #718

**Comment by thehomebrewnerd** [comment]
Closing this as the accessor implementation has been merged into main, and this is no longer an issue with that approach.
