### ISSUE TITLE
Support integer column names in Dask DataTables

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#445]
Dask DataTables can't handle integers as column names, not because Dask DataFrames can't handle them, but because of the way we update the DataFrame:

`self._dataframe[name] = column._series`
^ this gets interpreted as trying to index into the DataFrame with
`NotImplementedError: Item assignment with <class 'int'> not supported`

Once fixed, we should be able to avoid xfailing at `test_datatable_falsy_column_names`, and we should remove the reference to this limitation in the Dask guide.

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
