### ISSUE TITLE
Setting logical type of column to categorical results in categories of type object, instead of int

### ISSUE THREAD

**Issue by angela97lin** [alteryx/woodwork#466]
When setting the logical type of a column to categorical and then converting to a series, we get that the category is of type "object"; this is different from if a user were to just set the original series as a categorical type, which results in integer categories.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
import woodwork as ww

s = pd.Series([1, 2])
s_ww = ww.DataColumn(s)
s_ww.set_logical_type('categorical').to_series()
```

Produces:
```
0    1
1    2
dtype: category
Categories (2, object): [1, 2]
```

But
```
s.astype("category")
```

Produces:
```
0    1
1    2
dtype: category
Categories (2, int64): [1, 2]
```

Is this intentional behavior?

**Comment by tyler3991** [comment]
Closing. We have intended pandas behavior.
