### ISSUE TITLE
Improve storing of data for DataColumn and DataTable

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#471]
- Currently, we keep track of data in 2 places. The dataframe in the DataTable, and the series in the DataColumn. 
- This is certainly not ideal, we should find a better solution. Our current situation requires us to do some user hand holding, and make sure that changes on the DataTable are matched with the DataColumn (ex - remove a column from DataTable means taking it out from the dataframe, and removing it from the column dictionary (consisting of DataColumns).

## Option 1
- One way to resolve this is to keep the dataframe on the DataTable but remove the series being stored on the DataColumn.
- The DataColumn would keep track of only the metadata (logical types, semantic tags, etc) associated with that column. 
- If a user requested a specific column `datatable['total']`, Woodwork could create a DataColumn with a series (but this DataColumn would have no knowledge of the DataTable).
- Updates to the data would only happen on the dataframe on the DataTable

## Option 2
- Another solution was to have the DataColumn contain the DataTable that it is a part of. The data of the DataColumn would be referenced by looking at the dataframe of the DataTable.  
- Updates to the data would only happen on the dataframe on the DataTable

**Comment by tyler3991** [comment]
Closing. Will be addressed by #483
