### ISSUE TITLE
Add Koalas Table Accessor

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#493]
Allows Koalas DataFrames to use the `ww` namespace for accessors.

Involves adding any additional tests or validation that might be necessary with the new API.

**Comment by tamargrey** [comment]
In checking `_is_valid_schema`, we check that all they dtypes for each column match. We should make sure to use the backup dtype for koalas dataframes.

**Comment by tamargrey** [comment]
The `ks.set_option('compute.ops_on_diff_frames', True)` line will need to be added to `table_accessor.py` in a way that works in accordance with #543--so likely in the `WoodworkTableAccessor.init` method.

**Comment by thehomebrewnerd** [comment]
When adding support for Koalas, the function `_is_valid_latlong_value` will need to be updated to account for the need to use lists instead of tuples for latlong values in Koalas.

**Comment by thehomebrewnerd** [comment]
Closed by #652
