### ISSUE TITLE
Remove DataTable and DataColumn Classes

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#495]
Once the Schema and Accessor classes are fully implemented and we have feature parity or a plan to get to feature parity with the old API, we should remove the old classes and their tests.

**Comment by tamargrey** [comment]
Change `read_csv_to_accessor` to `read_csv` when removing what's currently the `read_csv` util function.

**Comment by tamargrey** [comment]
Change `load_retail_to_accessor` to `load_retail` after we remove the current `load_retail` function.

**Comment by thehomebrewnerd** [comment]
We should also consider updating the `sample_series` test fixture to return objects with the proper dtype rather than calling `convert_series` in our test to do this conversion. We might be able to elminate, or at least reduce the usage of the `convert_series` utility function.

**Comment by jeff-hernandez** [comment]
Closed by #713
