### ISSUE TITLE
Confirm feature parity with DataTables or determine future tasks to get there.

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#496]
We should do a more thorough walkthrough of the old API and the new API to make sure we haven't inadvertently lost or changed any behavior. 

If anything is found to be missing, create issues for the fixes before removing any of the DataTables code.

**Comment by gsheni** [comment]
We also think about this as we update the documentation with the new Accessor implementation.

**Comment by thehomebrewnerd** [comment]
From the Get Started guide:

The previous DataTable.head() method would display a dataframe with the column headers showing the Woodwork typing information. This behavior is not replicated in the current accessor approach.

**Comment by tamargrey** [comment]
@gsheni I know we've vaguely discussed not needing to add a `head` method like the one we added to DataTable, but just want to confirm that we're good to move forward with the Accessor without adding a `df.ww.head` that has Woodwork typing info as the column headers?

**Comment by gsheni** [comment]
@tamargrey yes we are good to go ahead without the head function.

**Comment by tamargrey** [comment]
Created issues for any features necessary to get to feature parity as well as actions to take once DataTables has been removed. Closing.
