### ISSUE TITLE
Allow updates to Series Accessor

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#524]
- As a user, I wish I could use the Woodwork Series Accessor to update the Logical Types or semantic tags of a series' Accessor.

```python
series = pd.Series(..)

series.ww.init()
series.ww.set_semantic_tags('new_tag')

assert 'new_tag' in series.ww.semantic_tags
```

Helper functions made for updating the column's dictionary of typing information are also relevant for #488.

**Comment by thehomebrewnerd** [comment]
Closing and replacing with two more specific issues: #565 and #567
