### ISSUE TITLE
Drop Python 3.6 Support

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#530]
- As numpy 1.20.0 drops support for python 3.6, we will be dropping support for it in an upcoming release.

**Comment by tyler3991** [comment]
ice boxing this issue on zenhub for now

**Comment by gsheni** [comment]
We can go ahead with this for now, as EvalML dropped Python 3.6 and Featuretools will be dropping support soon as well.

**Comment by tamargrey** [comment]
@gsheni I think we need to drop 3.6 support before we can add #264 because it'll require us to change our min pandas to 1.2.0, which only supports python 3.7 and up

**Comment by gsheni** [comment]
@tamargrey Gotcha. That's a good enough push to drop python 3.6 (especially since `numpy`, `evalml` have dropped support for it as well). Moved #530 into the top of our sprint.
