### ISSUE TITLE
Add df.ww.value_counts to Accessor

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#561]
Another method that will overwrite the Pandas operation

**Comment by tyler3991** [comment]
@tamargrey, is this going to happen in the near future? If so, i'll move to sprint backlog

**Comment by tamargrey** [comment]
@tyler3991 I figure describe and serialization should come first, but I'll keep making my way through these issues until we can move towards working on the Schema update issues, which are probably higher priority

**Comment by tyler3991** [comment]
@tamargrey got it, thanks!

**Comment by tyler3991** [comment]
Maintain current behavior that is in data table today

**Comment by gsheni** [comment]
Current Behavior --> https://woodwork.alteryx.com/en/latest/guides/statistical_insights.html#DataTable.value_counts
