### ISSUE TITLE
Preserve the underlying pandas DataFrame's index in initialization of Woodwork data structure

### ISSUE THREAD

**Issue by angela97lin** [alteryx/woodwork#569]
- As a user, I would like Woodwork to preserve the underlying pandas DataFrame's index if I did not specify a specific `index` column to use. Right now, in WW 0.0.8 and 0.0.9, the index is replaced with `RangeIndex`. However, in EvalML, we want to preserve the user input's index. This is currently tricky to do without adding a new index column and then removing it.

Talked to @tamargrey about https://github.com/alteryx/woodwork/pull/464; we agreed a happy balance could be: 
- If user doesn't specify `index` parameter in initialization of WW DataTable, use underlying Index.
- If user later sets `index` and then removes it, `RangeIndex` is a good default.

#### Code Example

```python
X_df = pd.DataFrame([0, 1, 2, 3, 4], index=list(range(-5, 0)))
X_ww = ww.DataTable(X_df)
assert X_ww.to_dataframe().index == list(range(-5, 0))
```

**Comment by jeff-hernandez** [comment]
> If user later sets `index` and then removes it, `RangeIndex` is a good default.
@angela97lin @tamargrey are there any drawbacks to also using the underlying index in this case too?

**Comment by tamargrey** [comment]
@jeff-hernandez I don't know about drawbacks, but I've sort of been viewing the situation in which you never set an index but have an underlying index as being different from when you expressly remove the index. In that second case, it seems odd to me that you'd have a remnant of that reset index left (but maybe it's fine or even desirable??)

I guess there's a number of situations when the index might have been removed more than just setting the index to None:

- If the whole index column itself has been removed inplace (DataTable.pop would be the only way of doing this, I think), then I'm pretty confident that we don't want the underlying index to still be that column that was removed--not leaving any remnants of the removed column.
- Using `DataTable.set_index` which creates a new DataTable object but can be used to set the index to None
- Reset it to None inplace 

All of these ^ seem like purposely getting rid of an index. But then there's this last way which feels more like a side effect, so maybe we would keep the underlying index?

- If the index column has been removed by virtue of creating a new DataTable from a selection of some of the columns (`dt[column_list]`). This feels more similar to creating a brand own new DataTable with your own underlying index. Maybe keep the underlying index?

Honestly, I'm not sure what users would expect.

**Comment by angela97lin** [comment]
I think you laid out the cases pretty well @tamargrey, and I'm not sure how much insight I can add. I agree that in the case where we're explicitly choosing to remove the index, it's a bit odd to have it keep track of and remember what it was initially set to. If the user really wanted that behavior, it is still possible for them to keep track of the original index and update, so I'm not too worried?

Maybe it's also important to note that there's a bit of a mismatch in behavior with this issue / grabbing the index from the original DF: We're able to set the index to something that doesn't exist in the DataTable. Yet, if users later want to manipulate the index in any way, they would need to specify a column in the DataTable. If they set it to something else, there's no way for them to set it back to the original index without adding that index as a column to the table. Interesting quirk worth pointing out 🤔

**Comment by jeff-hernandez** [comment]
I think it makes sense to remove the index when the user expressly removes it. I'm thinking more along the lines when a user creates a data table from a pandas data frame and leaves index to None. Are we assuming the user is expressly removing the index if the index parameter is None? I think the index is not included as a column in the data table by default, so how would a user set it as the index? Would they need to reset the index in pandas before passing it to the data table?

I see it similar pandas behavior where you have a data frame with index A, then set it to index B. You can only remove index B by resetting to index C and getting the default `RangeIndex` or by expressly setting the index back to A.

**Comment by angela97lin** [comment]
Oo I think in the case where the user doesn't specify the index, it should be set to the underlying dataframe's index, and not treated as user is expressively removing the index (which I think is current WW behavior).

**Comment by jeff-hernandez** [comment]
I see so when a user hasn't specified the index and wants to return back to a pandas data frame, that's when the underlying index gets changed.

**Comment by thehomebrewnerd** [comment]
I might not be following this exactly, but my initial reaction is that I do not think Woodwork should assume that the index is the dataframe index if the user doesn't specify an index column. I think the user should be explicit in what they want, and we should minimize the assumptions that Woodwork is making.

So, with that in mind, if the user initializes with `index=None`, as far as Woodwork is concerned, there is no index column in the dataframe. Maybe we can just leave the dataframe index alone in that case unless that creates other issues?

Along those same lines, I would also not make the assumption that `index=None` is the same as removing the index.

**Comment by jeff-hernandez** [comment]
It might be worth giving the user an option to set the index as the underlying pandas index as well.

```python
X_ww = ww.DataTable(X_df, index='index')
```
