### ISSUE TITLE
Replicate preserve index behavior implemented on DataTable

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#597]
PR #588 implemented changed to the way indexes are handled for DataTables. We should make sure this behavior is replicated with the new accessor approach.

**Comment by tamargrey** [comment]
We might need to move the semantic tag update methods to the Table Accessor. I stuck them on the Schema class because I was thinking that they don't care at all about the dataframe, but this change means they have to be able to reset the underlying index....
