### ISSUE TITLE
Review use of compute to validate LatLong data with Dask

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#627]
The initial accessor implementation uses a `.compute()` call to pull data into memory for validating that a series contains valid LatLong data when using Dask dataframes. This compute call is potentially expensive. We might want to consider removing this validation check for Dask instead.

Without the validation it would become possible for users to create a column as a LatLong logical type, even if the data did not fit the standard formatting. Removing the validation would put the burden on users to make sure their data was valid to prevent other downstream issues.

Current code for reference:
```python
def _is_valid_latlong_series(series):
    '''Returns True if all elements in the series contain properly formatted LatLong values,
    otherwise returns False'''
    dd = import_or_none('dask.dataframe')
    if dd and isinstance(series, dd.Series):
        series = series.compute()
    if series.apply(_is_valid_latlong_value).all():
        return True
    return False
```

**Comment by tyler3991** [comment]
note: adding this to next sprint starting on march 9  @thehomebrewnerd

**Comment by thehomebrewnerd** [comment]
Support for Dask dataframes is being dropped.
