### ISSUE TITLE
Calculate mutual information for continuous numerical columns with unique values.

### ISSUE THREAD

**Issue by angela97lin** [alteryx/woodwork#643]
https://github.com/alteryx/woodwork/pull/563 updated the implementation of `mutual_information` to avoid calculating mutual info for columns with completely unique values. This makes sense for columns such as id columns where every value in the column is supposed to be unique. The previous implementation of `mutual_information` would have considered two completely unique columns to have a high mutual info score.

However, it is very possible for two continuous numerical columns to have completely unique values and have a high mutual information score. For example, two columns that are [0.1, 0.2, 0.3, 0.4] or [0.1, 0.2, 0.3, 0.4] and [0.1, 0.2, 0.3, 0.5]. These columns should have a strong mutual info score. 

EvalML is currently using WW's mutual information method to calculate possibility of correlation, and for regression problems with many floats, we can no longer use the mutual info to detect possible correlation between columns that have unique values.

I think it could be a good idea to include continuous numeric columns even if they have completely unique values.

@tamargrey @freddyaboulton FYI, and thank you for your thoughts :)

**Comment by tyler3991** [comment]
I'm not sure how to move forward on this. @rpeck have you seen this yet? Any thoughts?

**Comment by tyler3991** [comment]
Leaving in "new issues" for now

**Comment by tyler3991** [comment]
This is now related to  #671, which is getting prioritized. I'll circle back on this issue and determine if it should be closed as a duplicate (@gsheni , @angela97lin , @dsherry )

**Comment by gsheni** [comment]
This issue will be resolved by: https://github.com/alteryx/woodwork/issues/676

**Comment by tyler3991** [comment]
Closing, track above link for status.
