### ISSUE TITLE
Add __setitem__ to WoodworkTableAccessor

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#647]
For feature parity with DataTables, we should be able to use `df.ww['new_col'] = series` to add or update a column.

For exact feature parity with DataTables, it should be required that the series has Woodwork typing information initialized. However, it'd also be possible to pass in a series without Woodwork typing initialized and for Woodwork to perform type inference on the data.

**Comment by thehomebrewnerd** [comment]
Closed by #669
