### ISSUE TITLE
Repr physical type is not changed when updating the LogicalType of a column with accessor

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#656]
When using `df.ww.set_types()` to change the logical type of a column, the repr does not properly display the updated dtype of the column. This is likely because the dtype item in the column dictionary is not getting updated, and this is the value that is used in the repr.

#### Code Sample

```python
>>> import pandas as pd
>>> import woodwork as ww
>>> 
>>> df = pd.DataFrame({
...     'integers': [-2, 30, 20],
...     'bools': [True, False, True],
...     'names': ["Jane Doe", "Bill Smith", "John Hancock"]
... })
>>> df
   integers  bools         names
0        -2   True      Jane Doe
1        30  False    Bill Smith
2        20   True  John Hancock
>>> df.ww.init()
>>> df.ww
         Physical Type Logical Type Semantic Tag(s)
Column                                             
integers         Int64      Integer     ['numeric']
bools          boolean      Boolean              []
names         category  Categorical    ['category']
>>> df.dtypes
integers       Int64
bools        boolean
names       category
dtype: object
>>> df.ww.set_types(logical_types={'names': 'FullName'})
>>> df.ww
         Physical Type Logical Type Semantic Tag(s)
Column                                             
integers         Int64      Integer     ['numeric']
bools          boolean      Boolean              []
names         category     FullName              []
>>> df.dtypes
integers      Int64
bools       boolean
names        string
dtype: object

```
After initialization, Woodwork infers the names column to be Categorical and the physical type shown in the repr is `category` as expected and is also the dtype of the column. However, after running `set_types` and changing the LogicalType to `FullName`, the repr still shows the physical type as `category` although the dataframe dtype is `string` which is what we expect to see in both places.

**Comment by tamargrey** [comment]
Would #653 fix this if the issue is indeed that we aren't updating the dtype field of the column dictionary?

**Comment by thehomebrewnerd** [comment]
> Would #653 fix this if the issue is indeed that we aren't updating the dtype field of the column dictionary?

Yes, but we would need to pull #653 into this epic in order to fix the issue. This problem is causing incorrect output in our documentation so it needs to be fixed so we can have correct documentation. 

We can either implement a simple fix for this issue here and work #653 separately, or pull #653 into this epic which *should* also close this issue.

**Comment by tamargrey** [comment]
@thehomebrewnerd I'm fine making a simple fix here in this epic and wait to do #653 until the improvements epic. But the fact that the redundant information already caused a bug probably means it should be relatively high priority.

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd I'm fine making a simple fix here in this epic and waiting to do #653 until the improvements epic. But the fact that the redundant information already caused a bug probably means it should be relatively high priority.

@tamargrey I agree on the priority of this issue. Just trying to a little mindful of not adding more than necessary to this initial epic, but it might be better to do the full fix and be done with it, rather than doing a quick patch.

@gsheni @tyler3991 We need to decide whether to implement a full update as described in #653 in the Accessor Improvements epic or a "quick fix" for this current epic.

**Comment by gsheni** [comment]
@thehomebrewnerd let's pull #653 into this epic as this is a relatively high priority bug, and I would like to avoid doing 2x the work than needed.

**Comment by thehomebrewnerd** [comment]
This issue has been resolved by recent changes to the way dtypes are handled in Woodwork. The output now matches expectations:

```python
>>> import pandas as pd
>>> import woodwork as ww
>>> df = pd.DataFrame({
...     'integers': [-2, 30, 20],
...     'bools': [True, False, True],
...     'names': ["Jane Doe", "Bill Smith", "John Hancock"]
... })
>>> df
   integers  bools         names
0        -2   True      Jane Doe
1        30  False    Bill Smith
2        20   True  John Hancock
>>> df.ww.init()
>>> df.ww
         Physical Type Logical Type Semantic Tag(s)
Column                                             
integers         Int64      Integer     ['numeric']
bools          boolean      Boolean              []
names         category  Categorical    ['category']
>>> df.dtypes
integers       Int64
bools        boolean
names       category
dtype: object
>>> df.ww.set_types(logical_types={'names': 'FullName'})
>>> df.ww
         Physical Type Logical Type Semantic Tag(s)
Column                                             
integers         Int64      Integer     ['numeric']
bools          boolean      Boolean              []
names           string     FullName              []
>>> df.dtypes
integers      Int64
bools       boolean
names        string
dtype: object
```
