### ISSUE TITLE
Bump min Koalas version to 1.7.0

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#659]
- The KoalasTableAccessor changes need to be able to use `df.insert` for `test_dataframe_methods_on_accessor_inplace` which is not present on `1.4.0`, which is currently the min version. 
- In addition, Koalas 1.7.0 [adds](https://github.com/databricks/koalas/releases/tag/v1.7.0) support for following new pandas Dtypes. This can help us remove the backup dtypes for a lot of our Logical Types.
  - Int8Dtype 
  - Int16Dtype
  - Int32Dtype
  - Int64Dtype
  - BooleanDtype
  - StringDtype
  - Float32Dtype
  - Float64Dtype

**Comment by thehomebrewnerd** [comment]
Closed by #678
