### ISSUE TITLE
Update backup_dtype to match actual series dtype

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#670]
In Woodwork we have implemented the concept of a `backup_dtype` on a LogicalType, primarily for Koalas which does not support all of dtypes that pandas supports. However, when defining backup_dtypes for certain logical types, we have not used the actual dtype, but rather the dtype string that the user would have to call to convert the series.

For example the Categorical logical type has `pandas_dtype = 'category'` and `backup_dtype = 'str'`. With Koalas, if you run `series.astype('str')` you get a series with a dtype of `object`.  If you run `series.astype('object')` an error is raised. Since we have been using the backup_dtype value in Woodwork for performing type conversions we defined the `backup_dtype` to be the value that was valid for passing to `astype`. This has created unintended consequences that impact what a user sees in Error messages and `repr` output as well as what gets checked by Woodwork when determining if a schema is valid for a given dataframe.

For consistency and clarity, we should define the `backup_dtype` to be the actual dtype of the series. For the Categorical logical type this would mean `backup_dtype = 'object'`. In places where we need to use `str` either in calls to `astype` or in our error messages, we could use a helper function to return this value based on the series library type and the logical type.

We should also consider renaming `pandas_dtype` to something more generic such as `primary_dtype`. Since we also currently use the `pandas_dtype` when working with Dask, the naming is mismatched and could be confusing.

This issue is related to both #653 and #656.

**Comment by tamargrey** [comment]
Now that we can use `string` as a backup dtype, the backup dtype will match the actual series dtype. There are still some dtype updates that should get made before we can complete #653 but those are now covered by #681. Closing
