### ISSUE TITLE
Spike: Investigate validation control 

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#679]
- How should the user control validation when loading in their data? How to disable it?
- What happens when deserialization data that is already been validated?
- Should validation be turned on/off for all DataFrames or just 1 DataFrame? 
- Should validation include everything or just some things? (columns unique, index uniqueness, time index DataTime check)
- How do we differentiate between Schema validation and data validation? 
- Deliverable: 
  - Plan for approaching with code examples.
  - Any additional issues that need to be created.

**Comment by thehomebrewnerd** [comment]
Outcome of the initial investigation has been documented in issue #620
