### ISSUE TITLE
Add update_dataframe to Accessor

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#705]
- We need a way to update the DataFrame with new data (even if the underlying dtypes do not match). The `df.ww.update_dataframe` would handle this because the Schema would already be initialized. 
- We will need this for the Featuretools implementation of Woodwork.

**Comment by thehomebrewnerd** [comment]
We should probably spend a little time thinking about how we want the API for this to work. With the accessor approach, I do not think we will be able to replace one initialized dataframe with another in-place, so a method like `df.ww.update_dataframe()` would need to return a new dataframe like this:

```python
new_df = df.ww.update_dataframe(new_df)
```

That is more-or-less the same as calling:
```python
new_df.ww.init(schema=df.schema)
```

With the second approach we would just need to make sure we handle column dtype conversions properly. Anyway, just wondering if we need an `update_dataframe` method, or if it would be sufficient to just cleanly allow initializing a new dataframe from and existing schema.

**Comment by tamargrey** [comment]
@thehomebrewnerd If I'm understanding correctly, you are suggesting that we allow `new_df.ww.init(schema=df.ww.schema)` to work in the situation where the dtypes between `df` and `new_df` do not match? In this case, as long as the data in `new_df` is viable for the logical types in the schema, it would still work and convert the dtypes in `new_df` to match the logical type dtypes?

This is a situation that we'd be allowing for:
```python
df.ww.init(logical_types={'id':'Integer')
schema = df.ww.schema

new_df = df.astype({'id':'string'})
new_df.ww.init(schema=schema)
assert new_df['id'].dtype == 'Int64'
```
However we'd also end up with something like this:
```python
df.ww.init(logical_types={'id':'Integer')
new_df = df.ww.astype({'id':'string'}) # previously this would Warn and remove Woodwork typing info
assert new_df.ww.schema is not None
assert new_df['id'].dtype == 'Int64' # Woodwork would convert back to the dtype in the schema
```

**Comment by thehomebrewnerd** [comment]
> If I'm understanding correctly, you are suggesting that we allow `new_df.ww.init(schema=df.ww.schema)` to work in the situation where the dtypes between `df` and `new_df` do not match?

Not necessarily - just suggesting we would need a solution for initializing from existing typing information when a dtype conversion might be needed.

**Comment by thehomebrewnerd** [comment]
I guess it just feels a little strange to me to call a method named `update_dataframe` and which doesn't really update a dataframe, but instead initializes and returns a dataframe. Maybe there is a way we can do the update in place that I'm not thinking about, like replacing columns one by one, although index differences might be problematic in that approach...

Probably worth a little deeper discussion before we launch into implementing something here.

**Comment by gsheni** [comment]
> With the second approach we would just need to make sure we handle column dtype conversions properly. Anyway, just wondering if we need an update_dataframe method, or if it would be sufficient to just cleanly allow initializing a new dataframe from an existing schema.

If column dtype conversions work with `df.ww.init` and a previous Schema, then I we probably don't need an `update_dataframe` method (and can close this issue). 

Do we currently have unit tests to cover this scenario? Looking [here](https://github.com/alteryx/woodwork/blob/schema-accessor/woodwork/tests/accessor/test_table_accessor.py), I don't see anything on a quick glance...

**Comment by thehomebrewnerd** [comment]
We definitely need to do a little work here to make it clean an easy to initialize from an existing Woodwork dataframe. The current schema init will fail if the dtypes don't match.

**Comment by gsheni** [comment]
After reading the discussion above, let's go ahead and close this issue. The `df.ww.init` approach is better. 

I opened a new issue for us to handle the dtype conversion situation: https://github.com/alteryx/woodwork/issues/725
