### ISSUE TITLE
Review/Update Documentation for Completeness

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#721]
After the accessor approach is implemented, we should review the current documentation and identify any gaps that exist in our explanations of the usage and capabilities of Woodwork.

Things to consider:
- Have we adequately discussed all the methods in the public API?
- Do we clearly show how to use table getitem and setitem to extract a column, add a column or replace a column (along with how names and semantic tags are handled if there is a mismatch between the dataframe/series info)?
- Is selection with `loc` or `iloc` adequately covered?

If multiple areas for improvement are identified, distinct issues can be created for each and they can be handled separately.

**Comment by tamargrey** [comment]
Another thing to consider could be important to explain: what is a valid Schema for a DataFrame/Series?

**Comment by thehomebrewnerd** [comment]
Suggested updates to REAME.md: https://github.com/alteryx/woodwork/pull/497#discussion_r596470252

**Comment by thehomebrewnerd** [comment]
Documentation review is complete and update needs have been captured in other issues:
Before accessor release: #726 and #727
Long Range Improvements: #728 

Since the review is complete for now and issue have been captured elsewhere, this issue can be closed.
