### ISSUE TITLE
Store value of `make_index` on WoodworkTableAccessor

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#744]
- As a Featuretools user, I wish I could use access the value of `make_index` that was used when initializing Woodwork. This would allow for some performance improvement in the Featuretools `EntitySet.concat` method.

Note: This is not a blocking issue for Featuretools, but would be nice to have.

**Comment by tamargrey** [comment]
@thehomebrewnerd Would there be any reason to use the value of `make_index` when initializing Woodwork with a schema? Or when validating whether the schema is still valid in `_make_dataframe_call`?

With DataTables' `update_dataframe` there was some logic surrounding that kind of thing, but I'm not sure if it's still relevant here.

**Comment by thehomebrewnerd** [comment]
@tamargrey I might be overlooking something, but don't think we need to worry about `make_index` when initializing with a schema, or validating that a schema is still valid.

I think this will mostly be useful for handling the proper validation that Featuretools does inside `EntitySet.concat`, and possibly in our new implementation of `Entity.update_data` (which would mostly be the same logic as in `DataTable.update_dataframe`). Seems like this could/should reside on the accessor and not the schema to me.
