### ISSUE TITLE
Spike: Determine a way for users to use old dtypes with Woodwork

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#790]
- In Woodwork, we use pd.StringDtype, pd.Float64Dtype, pd.Int64Dtype, and pd.BooleanDtype. These are newer, experimental dtypes that all support NaNs (shown as pd.NA).
- However, this results in use-cases where if the library does not support the new dtypes, it will error. 
  - The Woodwork user then has to use the custom type system. This errors when the user creates data with a unexpected physical dtype (which cannot be converted).  
- Therefore, we need to explore a better path to allow user to use object, int64, float64, np.bool_ dtypes with Woodwork.
- Completion: A design doc that shows how we will tackle this. 
  - A way to use old types with Woodwork
  - Also, explore how this would work with EvalML usage (can users use dataframes with old_dtypes + Woodwork typing in EvalML)
  
## Possible Solution 1
- Add old_dtype, and new_dtype to each Logical type.
- Have a global config option to switch between the 2 options. 
- Use old dtypes by default

## Possible Solution 2
- Add `ww.config.use_old_types()` and `ww.config.use_new_types()` 
- Use old dtypes by default

**Comment by thehomebrewnerd** [comment]
Still working on finalizing a few technical implementation details, but a path forward is mostly established and documented. Created issue #802 to track the implementation.
