### ISSUE TITLE
Determine if `use_standard_tags` should live on the ColumnSchema or WoodworkColumnAccessor

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#794]
It's currently on the WoodworkColumnAccessor, but if we want to follow the TableSchema does, it would live there.

Reason to store on ColumnAccessor:
- The TableSchema contains ColumSchemas, so we'd end up storing `use_standard_tags` in multiple places on a TableAccessor (note - this value doesn't change, so it's unlikely to get out of sync)

Reasons to store on ColumnSchema:
- For the Table schema/accessor, `use_standard_tags` lives on the schema
- A reason to store the value on the Schema is that if a user were to perform some operation on a ColumnSchema (say resetting tags), the tags should be able to follow `use_standard_tags`. 
- When copying a schema, the value of `use_standard_tags` should be able to be retained

Either way, `use_standard_tags` is not getting included in the equality check, so if we move it to the ColumnSchema, it should get added to its equality check. Otherwise, we should add it to the WoodworkColumnAccessor equality check.

**Comment by tamargrey** [comment]
@thehomebrewnerd started moving `use_standard_tags` onto the `ColumnSchema` and almost immediately ran into a bug where the value stored on a column got out of sync with the value stored on the table (at `__setitem__`) and spent some time thinking about when it's okay to reference the column's `use_standard_tags` vs the table's.

I'm having flashbacks to DataTables columns getting out of sync from the table and feeling like we shouldn't store `use_standard_tags` on the Column schema. 

I'm thinking we should keep `use_standard_tags` just on the Column accessor (which will only exist when there's no wider table that could have a mismatched value) even if it means that any changes a user makes to a ColumnSchema object directly that could update the tags (a behavior we don't expect a ton of) will need to have a `use_standard_tags` parameter passed in separately.

**Comment by thehomebrewnerd** [comment]
@tamargrey Another thought here...should `use_standard_tags` be a global config option instead, so that it either applies everywhere or nowhere instead of trying to control this at the individual table/column level?

If not, I think that keeping use_standard_tags on the accessor makes sense based on the scenario you discuss.

**Comment by tamargrey** [comment]
@thehomebrewnerd having it as a global config will be difficult because we want to default to `False` for Schemas and `True` for Accessors (for the Featuretools integration), so unless we want the config to somehow differentiate between schemas and accessors, it would make that difficult.

Something else that just occurred to me if we don't store the value on the ColumnSchema: How do we handle initializing with a ColumnSchema? 

`use_standard_tags` will be an attribute of the column accessor that's not on the Schema, so when we call `series.ww.init(schema=schema)` there won't be a `use_standard_tags` value to go off of. Even if we go with the default, it's **very** possible that the schema being passed in was initialized with `use_standard_tags=False`, so we could run into a situation where `series.ww.use_standard_tags` is True but a column that should have standard semantic tags does not have them.

At the table level, a schema is valid independent of its `use_standard_tags` value, but it will always be the case that the semantic tags will reflect the `use_standard_tags` value (unless the user has messed with them directly), and I'd like that to be the case for the column schema. 

I think my suggestion is this:

Do not pass `use_standard_tags` in at `series.ww.init(schema=schema)`. This is a single series and we have its logical type, so we do a manual check `if logical_type.standard_tags in self.semantic_tags` and use that to define `use_standard_tags`. That way, the series with Woodwork now defined will always have its semantic tags reflect its `use_standard_tags`.

**Comment by tamargrey** [comment]
Talked with @thehomebrewnerd and came up with the following to avoid storing `use_standard_tags` in two places on the TableSchema: Only store `use_standard_tags` on a per-column basis in `ColumnSchema`. 

This causes the following changes in Woodwork table behavior:
- Different columns in Woodwork can have different `use_standard_tags` values within the same table
- At init, `use_standard_tags` can either be a `bool` or a `dict[str -> bool] `. Any columns not included in the dictionary will default to the default `use_standard_tags` value 
- If a user is setting a new series without Woodwork initialized with `df.ww['new_col'] = pd.Series()`, the `use_standard_tags` value will be the default
