### ISSUE TITLE
Add is_schema_valid utility function

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#805]
- As a user, I wish Woodwork had a simple way for me to check if a TableSchema object is valid for a dataframe.

Currently this can be checked indirectly by trying to initialize woodwork on a dataframe with the schema. If it can be initialized, the operation will succeed, and if not an error will be raised. It would, however, be cleaner for users to check this via a helper function rather than having to implement a try/except block to check this.

#### Code Example

```python
def is_schema_valid(dataframe, schema):
"""Determines if the provided schema can be used to initialize Woodwork on the dataframe"""
    schema_valid = # Code to check schema validity here
    if schema_valid:
        return True
    return False

assert is_schema_valid(dataframe, valid_schema)
assert not is_schema_valid(dataframe, invalid_schema)
```

**Comment by freddyaboulton** [comment]
@thehomebrewnerd This would be great! I think it would also help users if `is_schema_valid` (or another related helper function) would tell users which columns invalidate the schema. That way they know what they need to change in order to fix it.
