### ISSUE TITLE
Add boolean column with bool dtype and no NaNs to sample_df

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#847]
- We want to make sure we have a dataframe with all dtypes when run our unit tests.
- So we should add a column with all Boolean values, and no NaNs, with a dtype of `bool`

**Comment by thehomebrewnerd** [comment]
Is the main concern here proper inference or something else? We have several inference-specific test fixtures that should cover these different scenarios, but those might also need to be updated to make sure we are covering our bases in terms of possible input dtypes and missing values.

**Comment by gsheni** [comment]
Closing in favor of https://github.com/alteryx/woodwork/issues/999
