### ISSUE TITLE
DataFrames in conftest should specify the dtypes

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#848]
- The dataframes in the conftest should be very explicit about the dtypes being used. 
- For example, [here](https://github.com/alteryx/woodwork/blob/main/woodwork/tests/conftest.py#L42)
## Code Example
```python
@pytest.fixture()
def sample_unsorted_df_pandas():
    return pd.DataFrame({
        'id': pd.Series([3, 1, 2, 0], dtype="Int64")
        'full_name': pd.Series(['Mr. John Doe', 'Doe, Mrs. Jane', 'James Brown', 'Ms. Paige Turner'], dtype="string"),
        'email': pd.Series(['john.smith@example.com', np.nan, 'team@featuretools.com', 'junk@example.com'], dtype="string"),
        'phone_number': pd.Series(['5555555555', '555-555-5555', '1-(555)-555-5555', '555-555-5555'], dtype="string"),
        'age': pd.Series([33, 25, 33, 57], dtype="int64"),
        'signup_date': pd.Series(pd.to_datetime(['2020-09-01', '2020-08-01', '2020-08-02', '2020-09-01']), dtype="datetime64[ns]"),
        'is_registered': pd.Series([True, False, True, True], dtype="boolean"),
    })
```

**Comment by not-so-rabh** [comment]
@gsheni May I take this up?

**Comment by gsheni** [comment]
@not-so-rabh yes, you can take this issue up. Thanks!

**Comment by thehomebrewnerd** [comment]
One thing to keep in mind is that the series dtype does get used in the inference process, so if specifying the dtype during dataframe creation results in a different dtype than pandas would have set, this _could_ change the resulting logical type that is inferred. Not exactly sure if that will happen here or not, but if it does we may need to add some new tests to make sure we are still covering things properly.

**Comment by gsheni** [comment]
Closing in favor of #999
