### ISSUE TITLE
Woodwork metadata cannot handle Series

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#873]
For Featuretools' secondary time index and last time index, Woodwork tables need to be able to store a pandas, koalas, or dask series as a value in its metadata dictionary. 

However, there are two issues with storing a Series this way:
1. WoodworkTableAccessor's table equality check does `self.metadata != other.metadata` which is not a valid way of comparing the equality of any series that might be in metadata
2. The `schema` property returns a deepcopy of the TableSchema, and Koalas raises an error, apparently, if you try and deepcopy a series like that: `TypeError: cannot pickle '_thread.RLock' object`

(these issues will be problems for both table and column metadata)

Below is a test that produces both of the above issues:
```python
def test_series_in_metadata(sample_df):
    series = sample_df['id'].copy()

    sample_df.ww.init(table_metadata={'series': series})
    assert sample_df.ww.metadata['series'] is series

    assert sample_df.ww.schema == sample_df.ww._schema

```

**Comment by gsheni** [comment]
I can think of 2 possible fixes:
1. We iterate through `metadata`. For each item in the dictionary, if the variable type is a Series, use the `Series.equals` function. I wonder if this is problematic for Koalas/Dask Series. 

2. We don't support Series type in `metadata`. 

On another note, can the `secondary time index and last time index` be stored as a column in the Woodwork DataFrame? We can just keep the column name in the `metadata` of the Woodwork DataFrame...

**Comment by thehomebrewnerd** [comment]
I'm not sure we want to support storage of Series or other arbitrary objects in the metadata in general, if we can avoid it. This seems like it could be a challenge from a serialization/deserialization perspective in addition to the equality and copying issues raised above.

**Comment by tamargrey** [comment]
So it seems like there's three potential places where Featuretools would want to put a series in the Woodwork metadata:
1. secondary time index - could potentially be a column on the DataFrame
2. last time index - could potentially be a column on the DataFrame
3. interesting values - cannot be a column on the DataFrame (but can be a list, potentially)

It seems like we have the ability on Featuretools' end to avoid storing a Series in the metadata, and we should probably take that opportunity, since I think I agree that we should have more restrictions around what can be in Woodwork metadata.

I guess the restrictions on what can be metadata are informed by its deepcopying, equality, and serialization ability. Not sure how to actually restrict that when setting the metadata, though. So maybe it's just a note we add near metadata in the docstrings.

**Comment by gsheni** [comment]
I agree with you @tamargrey that we should avoid Featuretools storing Series on the metadata. 

Created an issue to address this: https://github.com/alteryx/woodwork/issues/1022

Closing this issue now.
