### ISSUE TITLE
Add FractionalAge Logical Type

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#876]
- As a user, I wish I could use Woodwork with a **FractionalAge** Logical Type ([1.5, 2.4, 3.5]).
- This should use the `np.float64` dtype as the Physical Type.

**Comment by gsheni** [comment]
```python
class FractionalAge(LogicalType):
    """
    Examples:
        .. code-block:: python
            [1.5, 2.4, 3.5]
            [30.0, 62, 87.7]
    """
    primary_dtype = 'float64'
    standard_tags = {'numeric'}
```

**Comment by gsheni** [comment]
While serialization will change, this should not be a breaking change, as it just adding a new Logical Type (not removing/renaming an existing one).

**Comment by tamargrey** [comment]
@gsheni do we need to bump the serialization schema? from `11.1.0` to `11.1.1` maybe?

**Comment by gsheni** [comment]
@tamargrey Yes, we should bump the serialization schema version
