### ISSUE TITLE
Setting Schema attribute from Accessor doesn't update Schema

### ISSUE THREAD

**Issue by tamargrey** [alteryx/woodwork#918]
Our table and column Accessors allow users to access attributes and properties from `TableSchema` and `ColumnSchema` objects through the accessor, but we run into issues if a user tries to set those attributes from the Accessor.

```python
df = sample_df.copy()
df.ww.init()

assert df.ww.name is None

df.ww.name = 'name'

assert df.ww.name == 'name'
assert df.ww.schema.name is None
```

I first noticed this with `TableSchema.name` in performing a `drop` operation. The dataframe from above will produce the following situation because we pass the Schema's `name` attribute to the resulting DataFrame, not the Accessor's:

```python
assert df.ww.name == 'name'

dropped_df = df.ww.drop(['id'])
assert dropped_df.ww.name is None
assert dropped_df.ww.schema.name is None
```

This will be an issue with any attribute of a Column or Table Schema that does not have a `getter` or `setter` on the Accessor. 

We have not run into this with table metadata, because it's a mutable dictionary, so we can get that value and update it with no issues, but if someone were to try and reassign that value, we'd run into the same situation. 

My suggestion is to either add just properties to the Accessor, essentially telling users that if they want to reassign `name` or `metadata` they have to go through `._schema` (note that going through `.schema` won't work because it's a copy of the schema.)

```python
df = sample_df.copy()
df.ww.init()

assert df.ww.name is None

df.ww._schema.name = 'name'

assert df.ww.schema.name =='name'
assert df.ww.name == 'name'
```

The other option is to add both getters and setters so that users can perform `df.ww.name = 'new_name'`. I'm leaning towards this option.

**Comment by thehomebrewnerd** [comment]
> Our table and column Accessors allow users to access attributes and properties from `TableSchema` and `ColumnSchema` objects through the accessor

While we need to fix the current bug in the short-term, maybe we should revisit the behavior of passing down calls to the schema. If in the future we add new attributes to the `TableSchema` or `ColumnSchema` this type bug could reappear silently, unless we happen to remember to add a getter and setter to the accessor.

**Comment by tamargrey** [comment]
@thehomebrewnerd I wouldn't be opposed to reconsidering how we allow passing attributes from schemas to accessors. It seems like we will always need getters and setters, in which case, there's no reason to ever be accessing the schema attribute from the accessor. 

Probably worth confirming that there aren't any situations where we'd need it, but I'm not thinking of any right now.
