### ISSUE TITLE
Cannot serialize multiple tables to same directory and then deserialize

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#963]
With the current serialization implementation, users cannot serialize multiple Woodwork dataframes to the same directory and then deserialize them. This is because typing information is always stored in a file named `woodwork_typing_info.json`. If you serialize multiple files to the same path, this file will be overwritten making it impossible to deserialize all but the last dataframe that was serialized.

Additionally, the `woodwork_typing_info.json` is overwritten without warning, so users could potentially corrupt the data needed for deserialization and not know this happened until they attempt to deserialize.

At a minimum, we should raise an error if the `woodwork_typing_info.json` already exists, giving users the option to specify a different path without corrupting already existing data. It might be better yet to give users the ability to optionally specify a custom name for the typing information file on serialization and deserialization, allowing multiple tables to be serialized/deserialized at the same path.

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd
import woodwork as ww
from woodwork.deserialize import read_woodwork_table

df = pd.DataFrame({
    'id': [0, 1, 2, 3],
    'ints': [1, 10, 20, 100]
})
df2 = pd.DataFrame({
    'id': [0, 1, 2, 3],
    'bools': [True, False, False, True]
})

df.ww.init(name="first_dataframe")
df2.ww.init(name="second_dataframe")

df.ww.to_disk('.')
df2.ww.to_disk('.')  # This overwrites the json file from the line above without error or warning

new_df = read_woodwork_table('.')  # This deserializes the second table only
new_df.ww.name
```

```
'second_dataframe'
```

**Comment by gsheni** [comment]
Once https://github.com/alteryx/woodwork/issues/968 is complete, this will be irrelevant

**Comment by thehomebrewnerd** [comment]
> Once #968 is complete, this will be irrelevant

I think this is only true for parquet serialization, or other formats where we can store the metadata in a single serialized file. We will still need to store metadata somewhere for CSV, correct?
