### ISSUE TITLE
Update woodwork conda-forge meta.yaml file once moto dependency issues are resolved

### ISSUE THREAD

**Issue by thehomebrewnerd** [alteryx/woodwork#964]
There is currently an issue with moto dependencies on conda-forge, which was causing the woodwork tests to fail. Once `moto 2.0.8` is released on conda-forge this issue should be resolved. The main cause is that in the 2.0.7 release of moto, an werkzeug restriction was added to setup.py, but when this package was released on conda forge, this same restriction was not added to the moto meta.yaml file allowing an incompatible version of werkzeug to be installed and resulting in a `pip check` failure.

The woodwork test failures were resolved temporarily by restricting werkzeug to <2.0.0 in the woodwork feedstock. This allows all the Woodwork tests to all pass successfully.

Once moto has resolved their dependency issues, we should update the woodwork feedstock to remove werkzeug completely from the meta.yaml file since we don't directly depend on this for anything.

**Comment by gsheni** [comment]
conda-forge now has moto v2.0.10
- https://anaconda.org/conda-forge/moto

**Comment by gsheni** [comment]
Resolved in https://github.com/conda-forge/woodwork-feedstock/pull/17
