### ISSUE TITLE
Add total, progress and unit to describe callback

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#966]
- As a user, I wish I could use Woodwork to get total, progress and unit of my describe callback.
```json
- progress (int/float): the progress so far in the calculations
- total (int/float): the total number of calculations to do
- unit (str): what is the units of progress/total
```

**Comment by thehomebrewnerd** [comment]
@gsheni Do we want to make these new arguments required for the callback function? The reason I am asking is that we currently require that the callback accept a progress percent value and now if we pass progress and total, this becomes redundant information.

We could use `inspect.getrargspec` and make all of the callback arguments optional and only send back the values for which the callback function has arguments defined. That would give users a bit more flexibility in how they define the callback functions in case they don't want all of the information. The downside being our calling of the callback function will be a little slower as we would have to determine what information to send each time in some conditional statements.

**Comment by gsheni** [comment]
@thehomebrewnerd let's remove progress_percent from the callback.
