### ISSUE TITLE
Add Unknown Logical Type 

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#986]
- The Unknown Logical Type (with physical type of string) is used when a column cannot be inferred as a specific Logical Type.
```python
class Unknown(LogicalType):
    primary_dtype = 'string'
```
- https://github.com/alteryx/woodwork/blob/main/woodwork/type_sys/type_system.py
```python
from woodwork.logical_types import Unknown

DEFAULT_TYPE = Unknown
```

**Comment by thehomebrewnerd** [comment]
Just want to mention here, that if we implement this as the default logical type, columns will never be inferred as `NaturalLanguage` as currently we do not have an inference function defined for the `NaturalLanguage` logical type.

**Comment by gsheni** [comment]
@thehomebrewnerd yep that's right, and expected. I think for now we will put the burden on the user to set NaturalLanguage columns.
